### ISSUE TITLE
404 not found when using base prefix

### ISSUE THREAD

**Issue by damienroche** [FranciscoKloganB/vitesse-enterprise#135]
## Context (Environment)
I set a base url prefix in vite.config.ts
```
export default defineConfig({
  base: '/test/',
  ...
})
```

I ran `pnpm dev` but the page [http://localhost:4000/test/](http://localhost:4000/test/) is a 404 not found
I can't access to the page until I hard reload (cmd + maj + R) the page.
Same for hot-reload, after each I'm redirecting to the 404 page, and I have to hard reload.

**Comment by FranciscoKloganB** [comment]
Hello @damienroche, like I just told another user, I am in a job exchange process, consequently, I will look into this report, when I have some availability.

Thanks for your patience. 🙇🏻

**Comment by FranciscoKloganB** [comment]
Hello, again @damienroche I was unable to replicate this issue.

Tested in `development` and `production` using the following config with the current `main` branch (they were updated earlier today). I am on `Ubuntu 20.04`, Node `v16.13.1` and PNPM `7.1.0`.

```js
export default defineConfig({
    base: '/test/',
    ...remainingConfig
})
```

I also tested using just `base: 'test'` instead of `/test/`.

Hot reload worked in both cases:
- Ran `pnpm dev` then modified `<p>` in `src/core/pages/index.vue`. Page updated without 404 errors.
- Production access also worked fine.

This is either a system issue or a package that was solved by the dependency bumps made today.

I am going to close the issue, but if you keep having issues and you are able to provide more information/suspicions on the problem, feel free to reopen. 🙇🏻
